services:
  - type: web
    name: gearted-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://www.gearted.eu
      - key: CORS_ORIGIN
        value: https://www.gearted.eu,https://gearted.eu,https://admin.gearted.eu
      - key: DB_URI
        sync: false  # Set manually in Render dashboard for security
      - key: JWT_SECRET
        sync: false  # Set manually in Render dashboard for security
      - key: JWT_EXPIRATION
        value: 24h
      - key: AWS_ACCESS_KEY_ID
        sync: false  # Set manually in Render dashboard for security
      - key: AWS_SECRET_ACCESS_KEY
        sync: false  # Set manually in Render dashboard for security
      - key: AWS_S3_BUCKET
        value: gearted-images
      - key: AWS_REGION
        value: eu-north-1
