name: gearted
description: Marketplace pour l'échange d'équipements Airsoft

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.0
  dio: ^5.3.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  # Temporarily comment out Firebase to test basic functionality
  # firebase_core: ^2.15.0
  # firebase_auth: ^4.7.2
  # cloud_firestore: ^4.8.4
  # firebase_storage: ^11.2.5
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.0.4
  url_launcher: ^6.2.5
  http: ^1.2.1
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  geocoding: ^3.0.0
  connectivity_plus: ^5.0.2
  flutter_cache_manager: ^3.4.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
